#!/bin/sh
# $Id$
# elvis: alioth		-- Search Alioth (alioth.debian.org)
# ianb@erislabs.net 20030910
# adapted from sourceforge elvi

. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_alioth_searchtype  soft
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search Alioth (alioth.debian.org)
Local options:
  -type=
          soft         |        Software / Group
          skill        |        Skills
          people                People
                                Default: $SURFRAW_alioth_searchtype
                                Environment: SURFRAW_alioth_searchtype
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-t*=*)      setopt SURFRAW_alioth_searchtype  $optarg ;;
	*) return 1 ;;
    esac
    return 0
}


w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://alioth.debian.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://alioth.debian.org/search/?words=${escaped_args}&type_of_search=$SURFRAW_alioth_searchtype"
fi
