#!/bin/sh
# $Id$
# elvis: altavista	-- Search the web using Altavista (www.altavista.com)
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_altavista_results $SURFRAW_results
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the web using Altavista (www.altavista.com)
Local options:
  -results=NUM                  Number of search results returned
                                Default: $SURFRAW_altavista_results
				Environment: SURFRAW_altavista_results
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-results=*) setopt   SURFRAW_altavista_results $optarg	;;
	*) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.altavista.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.altavista.com/web/results?nbq=${SURFRAW_altavista_results}&pg=aq&aqmode=s&aqo=${escaped_args}"
fi
