#!/bin/sh
# $Id$
# elvis: amazon		-- Search the amazon.com bookstore
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_amazon_country	"$SURFRAW_lang"
def   SURFRAW_amazon_search	all
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search-string]
Description:
  Search amazon
Local options:
  -country=COUNTRY		Two letter domain-style country code
           com              |   Main amazon.com site (default)
           ca               |   Canada
           cn               |   China
           de               |   Germany
           fr               |   France
           jp               |   Japan
           uk                   UK
				Environment: SURFRAW_amazon_country, SURFRAW_lang
  -search=			Specialised search on topic
          all		    |   All products
	  auctions	    |   Auctions
	  books             |	Books
	  cars		    |   New Cars
	  classical         |	Classical Music
	  dvd		    |	DVD
	  electronics       |	Electronics
	  garden            |	Lawn & Patio
	  kitchen           |	Kitchen
	  music             |	Popular Music
	  outlet	    |   Outlet
	  photo 	    |	Camera & Photo
	  software          |	Software
	  toys		    |	Toys & Games
	  tools		    |	Tools & Hardware
	  vhs		    |	Video
	  videogames	    |   Video Games
	  zshops	    |   zShops
	  wireless	       	Mobile & Wireless
				Default: $SURFRAW_amazon_search
				Environment: SURFRAW_amazon_search

Examples:
  $w3_argv0 -search=books -country=uk -q The Lotus and The Robot
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-search=*)	setopt	SURFRAW_amazon_search		$optarg ;;
	-country=*)	setopt	SURFRAW_amazon_country		$optarg	;;
	*) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments

case "$SURFRAW_amazon_country" in
    uk) host=www.amazon.co.uk	      ;;
    de) host=www.amazon.de	      ;;
    fr) host=www.amazon.fr	      ;;
    jp) host=www.amazon.co.jp	      ;;
    ca) host=www.amazon.ca	      ;;
    cn|zh|zt) host=www.amazon.cn      ;;
    *)  host=www.amazon.com	      ;;
esac

if null "$w3_args"; then
    w3_browse_url "http://${host}/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    if [ $host = "www.amazon.cn" ] ; then
	url="http://${host}/search/search.asp?searchType=&searchWord=${escaped_args}&Go.x=0&Go.y=0&bestSaleNum=0"
    else
	url="http://${host}/exec/obidos/external-search?index=${SURFRAW_amazon_search}&keyword=${escaped_args}"
    fi
    w3_browse_url "${url}"
fi
