#!/bin/sh
# $Id$
# elvis: appwatch	-- Search entries on Appwatch (www.appwatch.com)
# version 0.1 by Ross Campbell rcampbel3@yahoo.com 8/1/2000
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search entries on Appwatch (www.appwatch.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.appwatch.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.appwatch.com/Linux/Users/find?q=${escaped_args}"
fi
