#!/bin/sh
# $Id$
# elvis: ask		-- Question the web using Ask Jeeves (www.ask.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Question the web using Ask Jeeves (www.ask.com)
Example:
  ask is jeeves gay?
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.ask.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.ask.com/web?q=${escaped_args}"
fi
