#!/bin/sh
# $Id$
# elvis: austlii		-- Search Australian Law docs (www.austlii.edu.au)
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_austlii_results $SURFRAW_results
def   SURFRAW_austlii_method  auto
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search Australian & world case law, legislation and policy documents
  at Austlii (www.austlii.edu.au), the Australian Legal Information
  Institute
Local options:
  -method=auto    |
          boolean |
	  any     |
	  all     |
	  phrase  |
	  legis   |
	  title
				Define search method
				Default: $SURFRAW_austlii_method
				Environment: SURFRAW_austlii_method
  -results=NUM                  Number of search results returned
                                Default: $SURFRAW_austlii_results
				Environment: SURFRAW_austlii_results
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
        -method=*)  setopt   SURFRAW_austlii_method  $optarg     ;;
	-results=*) setopt   SURFRAW_austlii_results $optarg	;;
	*) return 1 ;;
    esac
    return 0
}
w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.austlii.edu.au/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.austlii.edu.au/cgi-bin/sinosrch.cgi?method=${SURFRAW_austlii_method}&meta=%2Fau&query=${escaped_args}&results=${SURFRAW_austlii_results}&submit=Search&callback=on&mask_world=&mask_path="
fi
