#!/bin/sh
#
# AUTHOR: tczy, based on piratebay by J.R. Mauro
#
# DATE: Mon, 18 Jan 2010 13:37:00 +0100
#
# DESC: Elvi to search the web using Microsoft's Bing
# elvis: bing		-- Search the web using Microsoft's Bing (www.bing.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search the web using Microsoft's Bing (www.bing.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.bing.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.bing.com/search?q=${escaped_args}&go=&form=QBLH&filt=all"
fi
