#!/bin/sh
# $Id$
# elvis: britannica	-- Look up word in Encyclopedia Britannica (www.britannica.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Look up word in the Encyclopedia Britannica (www.britannica.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://"www.britannica.com/""
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://search.britannica.com/search?query=${escaped_args}"
fi
