#!/bin/sh
# $Id$
# elvis: cite		-- Search computer science papers (www.researchindex.com)
. surfraw || exit 1

w3_config_hook () {
defyn   SURFRAW_cite_citations 0
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
   Surfraw search CiteSeer (www.researchindex.com)

   Research Index is a scientific literature digital library that
   indexes the full text of spidered PDF and PS documents and performes
   sophisticated clustering and citation analysis on the results.

Local options:
  -cite                         Search citations rather than documents.
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-cite) setoptyn   SURFRAW_cite_citations 1	;;
	*) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://citeseer.ist.psu.edu/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    url="http://citeseer.ist.psu.edu/cis?q=${escaped_args}&cs=1"
    if ifyes SURFRAW_cite_citations; then
	url="${url}&submit=Search+Citations"
    fi
    w3_browse_url "$url"
fi
