#!/bin/sh
#
# AUTHOR: S.S.R. Oemrawsingh
#
# DATE: Mon Oct 26 2009
#
# DESC: Elvi to search cliki.net
# elvis: cliki		-- Search the common lisp wiki
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search the common lisp wiki
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.cliki.net/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.cliki.net/site/search?query=${escaped_args}"
fi
