#!/bin/sh
# $Id$
# elvis: cnn		-- Search on CNN (cnn.com)
# version 0.1 by Ross Campbell rcampbel3@yahoo.com
# version 0.2 updated url
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search on CNN (search.cnn.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://cnn.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.cnn.com/search/?query=${escaped_args}&x=0&y=0&primaryType=mixed"
fi
