#!/bin/sh
# $Id$
# elvis: cnn		-- Search on CNN (cnn.com)
# version 0.1 by Ross Campbell rcampbel3@yahoo.com
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search on CNN (search.cnn.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://cnn.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://search.cnn.com/query.html?sites=CNN&qc=&col=cnni&qm=0&st=1&nh=20&lk=1&rf=1&look=&key=&venue=all&keyword=&qp=&comefrom=izcb-search&isp=zcb&search=0&qt=${escaped_args}"
fi
