#!/bin/sh
# Moritz Muehlenhoff <jmm@inutil.org>
# elvis: cve		-- Search for CAN assignments in CVE
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search for CAN assignments in the CVE dictionary
Example:
  cve CAN-2005-0666
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://cve.mitre.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://cve.mitre.org/cgi-bin/cvename.cgi?name=${escaped_args}"
fi
