#!/bin/sh
# elvis: ddg            -- Securely search the web using duckduckgo (www.duckduckgo.com)
# coder@kyleisom.net 20110105
# relevant: https://duckduckgo.com/params.html
# similar to duckduckgo elvi, adds more options and defaults to SSL.
. surfraw || exit 1

w3_config_hook () {
    def     SURFRAW_ddg_results             "$SURFRAW_results"
    def     SURFRAW_ddg_base_url            "www.duckduckgo.com"
    def     SURFRAW_ddg_search              search
    def     SURFRAW_ddg_params              "&kg=g"
    defyn   SURFRAW_ddg_https_arg           0
    defyn   SURFRAW_ddg_safe_arg            0
    defyn   SURFRAW_ddg_redirect_arg        0
    defyn   SURFRAW_ddg_use_javascript      0
    defyn   SURFRAW_ddg_got_a_ducky_feeling 0
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the web using DuckDuckGo (www.duckduckgo.com)
Local options:
    -d,-ducky,-l,-lucky         use in case of overwhelming feeling of duckiness
    -j,-javascript              use javascript
    -p,-safe                    enable safe search
    -r,-redirect                use redirection
    -s,-insecure                disable SSL search
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -d*|-l*)            setoptyn    SURFRAW_ddg_got_a_ducky_feeling 1 ;;
    -j|-javascript*)    setoptyn    SURFRAW_ddg_use_javascript      1 ;;
    -p|-safe*)		setoptyn    SURFRAW_ddg_safe_arg            1 ;;
    -r|-redirect*)      setoptyn    SURFRAW_ddg_redirect_arg        1 ;;
    -s|-sec*)           setoptyn    SURFRAW_ddg_https_arg           1 ;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
    
if [ "${SURFRAW_ddg_https_arg}" = 0 ] ; then
    SURFRAW_ddg_base_url="https://${SURFRAW_ddg_base_url}"
else
    SURFRAW_ddg_base_url="http://${SURFRAW_ddg_base_url}"
fi

# need to send the user to the non-javascript version if using a non-graphical
# browser
if [ "$SURFRAW_ddg_use_javascript" = 0 ]; then
    SURFRAW_ddg_base_url="${SURFRAW_ddg_base_url}/lite"
fi

if [ "$SURFRAW_ddg_safe_arg" = 1 ]; then
    SURFRAW_ddg_params="${SURFRAW_ddg_params}&kp=1"
fi

if [ "$SURFRAW_ddg_redirect_arg" = 1 ] ; then
    SURFRAW_ddg_params="${SURFRAW_ddg_params}&kd=1"
fi

if [ "$SURFRAW_graphical" != "yes" ] ; then
    SURFRAW_ddg_params="${SURFRAW_ddg_params}&kf=-1&kz=-1&kq=-1&kv=-1"
fi

escaped_args=`w3_url_of_arg $w3_args`
if [ "$SURFRAW_ddg_got_a_ducky_feeling" = 1 ]; then
    escaped_args="! ${escaped args}"
fi

w3_browse_url "${SURFRAW_ddg_base_url}/?q=${escaped_args}${SURFRAW_ddg_params}"
