#!/bin/sh
# jbr20050112
# elvis: deblogs		-- Show changelogs for a package in Debian main (changelogs.debian.net)

. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
Show changelogs for a package in Debian main (changelogs.debian.net)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
	w3_browse_url "http://changelogs.debian.net/"
else
    escaped_args=`w3_url_of_arg $w3_args`
	w3_browse_url "http://changelogs.debian.net/${escaped_args}"
fi
