#!/bin/sh
# $Id$
# elvis: deja		-- Search usenet using Deja News (www.dejanews.com)
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_deja_results $SURFRAW_results
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search the usenet using Deja-News (www.dejanews.com)
Local options:
  -results=NUM                  Number of search results returned
                                Default: $SURFRAW_deja_results
                                Environment: $SURFRAW_deja_results
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-results=*) setopt   SURFRAW_deja_results $optarg	;;
	*) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.dejanews.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://x25.deja.com/=dnc/[ST_rn=ps]/qs.xp?ST=PS&svcclass=dnserver&QRY=${escaped_args}&defaultOp=AND&DBS=1&OP=dnquery.xp&LNG=ALL&showsort=date&test=PS&maxhits=${SURFRAW_deja_results}"
fi
