#!/bin/sh
# jbr20050112
# elvis: etym		-- Look up word origins at www.etymonline.com
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Look up word origins at www.etymonline.com
Example:
  etym surf
  '1685, probably from earlier suffe (1599), of uncertain origin...'
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.etymonline.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.etymonline.com/?search=${escaped_args}"
fi
