#!/bin/sh
# $Id$
# elvis: excite		-- Search on Excite (www.excite.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search on Excite (www.excite.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.excite.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
	w3_browse_url "http://msxml.excite.com/_1_Y5CUB602ZUH3__info.xcite/dog/results?otmpl=dog/webresults.htm&qcat=web&foo=bar&qk=20&fs=infospace_excite_search&stype=web&qkw=${escaped_args}&top=1&start=&ver=31756"
fi
