#!/bin/sh
# jbr20050112
# elvis: foldoc		-- The Free On-Line Dictionary Of Computing (foldoc.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [search words]...
Description:
  The Free On-Line Dictionary Of Computing (foldoc.org)
Example:
  foldoc pcmcia
  "Personal Computer Memory Card International Association(*).
   (Or People Can't Memorise Computer Industry Acronyms)."
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.foldoc.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://foldoc.org/${escaped_args}"
fi
