#!/bin/sh
# $Id$
# elvis: freshmeat	-- Search Freshmeat (www.freshmeat.net)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search Freshmeat (www.freshmeat.net)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.freshmeat.net/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://freshmeat.net/search?q=${escaped_args}"
fi
