#!/bin/sh
# $Id$
# elvis: fsfdir		-- Search the FSF/UNESCO Free Software Directory (directory.fsf.org)
. surfraw || exit 1


w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search the FSF/UNESCO Free Software Directory (directory.fsf.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://directory.fsf.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
	w3_browse_url "http://directory.fsf.org/search/?query=${escaped_args}"
fi
