#!/bin/sh
# $Id$
# elvis: ftpfind		-- Search files on ftpfind (www.ftpfind.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search files on www.ftpfind.com (www.ftpfind.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://"www.ftpfind.com/index.php?adv=true""
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.ftpfind.com/search.php?query=${escaped_args}&method=iss"
fi
