#!/bin/sh
# elvis: genbugs		-- Search the Gentoo bug tracker (bugs.gentoo.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [search words]...
Description:
  Surfraw search the Gentoo bug tracker (bugs.gentoo.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments

if test -z "$w3_args"; then
    w3_browse_url "http://bugs.gentoo.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
	terms=`echo $escaped_args | sed 's/%20/+/g'`
	w3_browse_url "http://bugs.gentoo.org/buglist.cgi?quicksearch=${terms}"
fi
