#!/bin/sh
#
# Original Author: J.R. Mauro
#
# Modified to use Gentoo Portage Overlays
# as gentoo-portage.com has gone -- ianb
#
# elvis: genportage	-- Search gentoo-portage.com for packages
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search gentoo portage overlays for packages
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://gpo.zugaina.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://gpo.zugaina.org/Search?search=${escaped_args}"
fi
