#!/bin/sh
# Linux Game Tome plugin (http://www.happypenguin.org)
#                                      jmm@informatik.uni-bremen.de
# $Id$

. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [search words]...
Description:
  Surfraw search for the Linux Game Tome (http://www.happypenguin.org)
EOF
    w3_global_usage
}

w3_config
# disable requoting, doesn't work with this elvi.
SURFRAW_quote_ifs=0
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.happypenguin.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.happypenguin.org/list?search=${escaped_args}"
fi
