#!/bin/sh
# $Id$
# elvis: lsm		-- Search the Linux Software Map
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_lsm_search title
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search the Linux Software Map (www.boutell.com/lsm/)
Local options:
  -search=                      Specialized search on topic
          title         |       Title search (default)
          keyword               Keyword search
                                Environment: SURFRAW_lsm_search
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -s*=*)  setopt   SURFRAW_lsm_search  $optarg ;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.boutell.com/lsm/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    if [ "$SURFRAW_lsm_search" = "keyword" ]; then
	url="http://www.boutell.com/lsm/lsmbykey.cgi/submit?keyword=${escaped_args}"
    else
	url="http://www.boutell.com/lsm/lsmbytitle.cgi/submit?title=${escaped_args}"
    fi
    w3_browse_url "${url}"
fi
