#!/bin/sh
# ianb@erislabs.net 20130923
# elvis: mdn		-- Search the mozilla developer network (developer.mozilla.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [search words]...
Description:
  Surfraw search the mozilla developer network (developer.mozilla.org)
EOF
    w3_custom_search_usage
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"
then
    w3_browse_url "http://developer.mozilla.org"
else
    w3_custom_search -s=developer.mozilla.org "$w3_shquoted_args"
fi


