#!/bin/sh
# $Id$
# elvis: raging		-- Search the web using Raging (www.raging.com)
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_raging_results $SURFRAW_results
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the web using Raging (www.raging.com)
Local options:
  -results=NUM                  Number of search results returned
                                Default: $SURFRAW_raging_results
				Environment: SURFRAW_raging_results
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-results=*) setopt   SURFRAW_raging_results $optarg	;;
	*) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.raging.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://ragingsearch.altavista.com/cgi-bin/query?FFF=off&wfmt=d&nbq=${SURFRAW_raging_results}&q=${escaped_args}"
fi
