#!/bin/sh
# elvis: scitopia	-- Search for science with scitopia.org
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search for science with scitopia.org
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments

if test -z "$w3_args"; then
    w3_browse_url "http://www.scitopia.org/scitopia/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://wwwscitopia.org/scitopia/result-list/fullRecord:${escaped_args}"
fi
