#!/bin/sh
# $Id$
# elvis: scpan		-- Search the Comprehensive Perl Archive Network (search.cpan.org)
# ianb@erislabs.net 20030918
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_scpan_search all
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the Comprehensive Perl Archive Network (search.cpan.org)
Local options:
  -search=                      Search Type
          all     |             All
          module  |             Modules
          dist    |             Distributions
          author                Authors
                                Default: $SURFRAW_scpan_search
                                Environment: SURFRAW_scpan_search
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -search=*)  setopt   SURFRAW_scpan_search  $optarg ;;
	*) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://search.cpan.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
	w3_browse_url "http://search.cpan.org/search?query=${escaped_args}&mode=${SURFRAW_scpan_search}"
fi
