#!/bin/sh
# $Id$
# elvis: slashdot	-- Search stories on Slashdot (www.slashdot.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search articles on Slashdot (www.slashdot.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.slashdot.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.slashdot.org/index2.pl?fhfilter=${escaped_args}"
fi
