#!/bin/sh
# $Id$
# elvis: slinuxdoc	-- Search entries in LDP (www.linuxdoc.org)
# version 0.1 by Ross Campbell rcampbel3@yahoo.com 8/1/2000
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search entries in LDP (www.linuxdoc.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.tldp.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.google.com/cse?cx=017644269519104757279%3Agm62gtzaoky&q=${escaped_args}&sa=go"
fi
