#!/bin/sh
# $Id$
# elvis: swhois		-- Search Whois (www.geektools.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search Whois (www.geektools.com/cgi-bin/proxy.cgi)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.geektools.com/cgi-bin/proxy.cgi"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.geektools.com/cgi-bin/proxy.cgi?query=${escaped_args}&targetnic=auto&btnGo=Whois+%BB"
fi
