#!/bin/sh
# $Id$
# elvis: wayback		-- Search The Internet Archive's Wayback Machine for a URL (archive.org)
. surfraw || exit 1
w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [URL]
Description:
  Search The Internet Archive's Wayback Machine for a URL (archive.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.archive.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    url="http://www.archive.org/searchresults.php?mediatype=web&Submit=Take+Me+Back"
    w3_browse_url "${url}&search=${escaped_args}"
fi
