#!/bin/sh
# $Id$
# elvis: wetandwild	-- Real time weather information (many sources)
. surfraw || exit 1


w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [city[,state][;country]]
Description:
  Surfraw real time weather information (weather channel)
Bugs:
  This elvi is named "wetandwild" instead of "weather" due to
  conflicts with a common tcl/expect script of the same name.
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.weather.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.weather.com/search/enhanced?whatprefs=&what=WeatherLocalUndeclared&lswe=&lswa=&from=whatwhere&where=${escaped_args}"
fi
