#!/bin/sh
# $Id$
# elvis: xxx		-- Superior XXX, hot and ready to press (arXiv.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options]
Description:
  Surfraw the Los Alamos XXX science E-Print Archive
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
w3_browse_url "http://arXiv.org/"
