#!/bin/sh
# elvis: yubnub		-- Use the social command-line for the web (yubnub.org)
# initial implementation by Iain D Broadfoot, ripped from the freshmeat elvi
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [command] [arguments]
Description:
    Run a yubnub command
EOF
    w3_global_usage
}

w3_config
# disable requoting, yubnub commands often need protecting from
# the shell with quotes but without those quotes passed on to yubnub
SURFRAW_quote_ifs=0
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.yubnub.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://yubnub.org/parser/parse?command=${escaped_args}"
fi
