.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SURFRAW 1 "mar 3, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
surfraw \- a fast unix command line interface to WWW services
.SH SYNOPSIS
.B surfraw
.RI [ options ]\ search_words...
.SH DESCRIPTION
This manual page documents briefly the
.B surfraw 
commands. 
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
It could be incomplete and/or not so up-to-date.
.br
See /usr/share/doc/surfraw/README for documentation.
.br
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBsurfraw\fP provides a fast unix command line interface to a variety
of popular WWW search engines and other artifacts of power. It
reclaims google, altavista, dejanews, freshmeat, research index,
slashdot and many others from the false-prophet, pox-infested heathen
lands of html-forms, placing these wonders where they belong, deep in
unix heartland, as god loving extensions to the shell.
.SH OPTIONS
Global options:
.br
.sp 1
.TP
.B \-help
Show summary of options (local options too).
.TP
.B \-version
Show version of program.
.TP
.B \-browser=EXECUTABLE           
Set browser (default: links)
.TP
.B \-elvi  
Display a list of other Surfraw mechanims for conquering evil
.TP
.B \-escape\-url\-args=yes\|no       
Apply url escaping to arguments (default: yes)
.TP
.B \-p0rn=yes\|no                  
Yes, yes, harder, deeper, faster, oh baybe (default: yes)
.TP
.B \-q\|quote
Bracket arguments with \" characters (default: no)
.TP
.B \-quiet=yes\|no                 
I can't enjoy it with you talking all the time (default: no)
.br
.SH AUTHOR
This manual page was written by Christian Surchi <csurchi@debian.org>,
for the Debian GNU/Linux system (but may be used by others).

